[project]
name = "ttail"
version = "0.3.1"
author = "Oliver Broman"
description = "Trace Tailer - Notepad highlighter"
readme = "README.md"
packages = [
    { include = "ttail", from = "src" }
]
requires-python = ">=3.14"
dependencies = [
    "pyqt6>=6.10.2",
]
